### ISSUE TITLE
Simple example doesnot work

### ISSUE THREAD

**Issue by bhargodevarya** [alex-shpak/rx-jersey#11]
I am trying to ue rx-jersey to return a Single from an endpoint created using jersey.
I followed the simple instructions given in the gitbook.
Still I get 500 error response.

Here is my code.
https://github.com/bhargodevarya/JerseyBackendExp

public class Main {
    public static final String BASE_URI = "http://localhost:8080/myapp/";
    public static HttpServer startServer() {
        final ResourceConfig rc = new ResourceConfig().packages("JeyseyBackendExp");
        rc.register(RxJerseyServerFeature.class);
        rc.register(RxJerseyClientFeature.class);
        return GrizzlyHttpServerFactory.createHttpServer(URI.create(BASE_URI), rc);
    }
   public static void main(String[] args) throws IOException {
        final HttpServer server = startServer();
        System.out.println(String.format("Jersey app started with WADL available at "
                + "%sapplication.wadl\nHit enter to stop it...", BASE_URI));
        System.in.read();
        server.stop();
    }
}

The resource being returned is :-

@Path("myresource")
public class MyResource {
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("test")
    public String getIt() {
        return "Got it!";
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("rx")
    public Single<String> rxSetup() {
        return Single.just("rx setup done");
    }
}

**Comment by bhargodevarya** [comment]
I changed to 
@GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("rx")
    public Single<User> rxSetup() {
        User user = new User();
        user.setAge(7);
        return Single.just(user);
    }

and in pom.xml added
<dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-binding</artifactId>
        </dependency>

Now I get the below response on my browser

{}

**Comment by alex-shpak** [comment]
Hi!

You have Jersey 2.27 in dependencies which is not supported yet, unfortunately. But it's in WIP state.
Currently Jersey 2.26 is supported.

Will add note to readme file

**Comment by alex-shpak** [comment]
Ah, sorry, I misread version.
It's `2.25` which is last supported (before they introduced injection facade)

**Comment by bhargodevarya** [comment]
I added 2.25.1 for jersey and 2.0.8 for rxJava after looking at
https://github.com/alex-shpak/rx-jersey/blob/master/gradle.properties

Now I get the following exception:

java.lang.NullPointerException
	at net.winterly.rxjersey.server.RxGenericBodyWriter.writeTo(RxGenericBodyWriter.java:80)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:934)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:966)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:922)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onSuccess(MaybeCallbackObserver.java:70)
	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver.onSuccess(MaybeSwitchIfEmpty.java:75)
	at io.reactivex.internal.operators.maybe.MaybeDelayWithCompletable$DelayWithMainObserver.onSuccess(MaybeDelayWithCompletable.java:102)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle$FromSingleObserver.onSuccess(MaybeFromSingle.java:76)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:2702)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:3724)
	at io.reactivex.internal.operators.maybe.MaybeDefer.subscribeActual(MaybeDefer.java:48)
	at io.reactivex.Maybe.subscribe(Maybe.java:3724)
	at io.reactivex.internal.operators.maybe.MaybeDelayWithCompletable$OtherObserver.onComplete(MaybeDelayWithCompletable.java:70)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.onComplete(FlowableFlatMapCompletableCompletable.java:163)
	at io.reactivex.internal.subscriptions.EmptySubscription.complete(EmptySubscription.java:68)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:61)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapCompletableCompletable.subscribeActual(FlowableFlatMapCompletableCompletable.java:56)
	at io.reactivex.Completable.subscribe(Completable.java:1635)
	at io.reactivex.internal.operators.maybe.MaybeDelayWithCompletable.subscribeActual(MaybeDelayWithCompletable.java:38)
	at io.reactivex.Maybe.subscribe(Maybe.java:3724)
	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty.subscribeActual(MaybeSwitchIfEmpty.java:38)
	at io.reactivex.Maybe.subscribe(Maybe.java:3724)
	at io.reactivex.Maybe.subscribeWith(Maybe.java:3790)
	at io.reactivex.Maybe.subscribe(Maybe.java:3711)
	at io.reactivex.Maybe.subscribe(Maybe.java:3677)
	at net.winterly.rxjersey.server.rxjava2.MaybeMethodDispatcher.dispatch(MaybeMethodDispatcher.java:42)
	at net.winterly.rxjersey.server.RxMethodDispatcher.dispatch(RxMethodDispatcher.java:47)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
May 10, 2018 2:42:20 AM org.glassfish.jersey.process.JerseyProcessingUncaughtExceptionHandler uncaughtException
WARNING: Unhandled exception detected on thread grizzly-http-server-0.
java.lang.NullPointerException
	at net.winterly.rxjersey.server.RxGenericBodyWriter.writeTo(RxGenericBodyWriter.java:80)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:934)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:966)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:922)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onSuccess(MaybeCallbackObserver.java:70)
	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver.onSuccess(MaybeSwitchIfEmpty.java:75)
	at io.reactivex.internal.operators.maybe.MaybeDelayWithCompletable$DelayWithMainObserver.onSuccess(MaybeDelayWithCompletable.java:102)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle$FromSingleObserver.onSuccess(MaybeFromSingle.java:76)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:2702)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:3724)
	at io.reactivex.internal.operators.maybe.MaybeDefer.subscribeActual(MaybeDefer.java:48)
	at io.reactivex.Maybe.subscribe(Maybe.java:3724)
	at io.reactivex.internal.operators.maybe.MaybeDelayWithCompletable$OtherObserver.onComplete(MaybeDelayWithCompletable.java:70)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.onComplete(FlowableFlatMapCompletableCompletable.java:163)
	at io.reactivex.internal.subscriptions.EmptySubscription.complete(EmptySubscription.java:68)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:61)
	at io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapCompletableCompletable.subscribeActual(FlowableFlatMapCompletableCompletable.java:56)
	at io.reactivex.Completable.subscribe(Completable.java:1635)
	at io.reactivex.internal.operators.maybe.MaybeDelayWithCompletable.subscribeActual(MaybeDelayWithCompletable.java:38)
	at io.reactivex.Maybe.subscribe(Maybe.java:3724)
	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty.subscribeActual(MaybeSwitchIfEmpty.java:38)
	at io.reactivex.Maybe.subscribe(Maybe.java:3724)
	at io.reactivex.Maybe.subscribeWith(Maybe.java:3790)
	at io.reactivex.Maybe.subscribe(Maybe.java:3711)
	at io.reactivex.Maybe.subscribe(Maybe.java:3677)
	at net.winterly.rxjersey.server.rxjava2.MaybeMethodDispatcher.dispatch(MaybeMethodDispatcher.java:42)
	at net.winterly.rxjersey.server.RxMethodDispatcher.dispatch(RxMethodDispatcher.java:47)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)

**Comment by alex-shpak** [comment]
Here is `pom.xml` that worked for me
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>JeyseyBackendExp</groupId>
    <artifactId>JeyseyBackendExp</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>JeyseyBackendExp</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.glassfish.jersey</groupId>
                <artifactId>jersey-bom</artifactId>
                <version>${jersey.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.glassfish.jersey.containers</groupId>
            <artifactId>jersey-container-grizzly2-http</artifactId>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.9</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.reactivex.rxjava2/rxjava -->
        <dependency>
            <groupId>io.reactivex.rxjava2</groupId>
            <artifactId>rxjava</artifactId>
            <version>2.1.13</version>
        </dependency>
        <dependency>
            <groupId>net.winterly.rxjersey</groupId>
            <artifactId>rxjava2-server</artifactId>
            <version>0.10.1</version>
        </dependency>
        <dependency>
            <groupId>net.winterly.rxjersey</groupId>
            <artifactId>rxjava2-client</artifactId>
            <version>0.10.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-server</artifactId>
            <version>${jersey.version}</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.containers</groupId>
            <artifactId>jersey-container-grizzly2-servlet</artifactId>
            <version>${jersey.version}</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
            <version>${jersey.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.3</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.5.1</version>
                <inherited>true</inherited>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.2.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>JeyseyBackendExp.Main</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <properties>
        <jersey.version>2.25.1</jersey.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>
```

Also don't forget to register Jackson geature
```java
rc.register(JacksonFeature.class);
```

**Comment by alex-shpak** [comment]
Feel free to reopen if you still have issue.

**Comment by pmiddend** [comment]
I have the same `NullPointerException` and did what you said (registering JacksonFeature and adding the dependency to the pom).

**Comment by alex-shpak** [comment]
Can you please share stack trace? I guess it same issue with Jersey versions.
